import Icons from "../basil-icons/icons"

//Icons arrays
const icons = []
export const version = 1.0;

//Push individual icons into array

export const pushSVG = (name: string, content: string, category: string, style?: string, tags?: string[]) => {
    icons.push({
        name: name,
        content: content,
        category: category,

        style: style,
        tags: tags,

        toSvg: () => {
            if (category == 'Feather Icons')
                return ('<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' + content + '</svg>')
            else
                return ('<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">' + content + '</svg>')
        },
    })
}

//Icon Initialisations

///Outline

//General
pushSVG('Home', Icons.Outline.Home, 'General', 'Outline')
pushSVG('Bag', Icons.Outline.Bag, 'General', 'Outline', ['Suitcase'])
pushSVG('Pie Chart', Icons.Outline.ChartPie, 'General', 'Outline')
pushSVG('Pie Chart-Alt', Icons.Outline.ChartPieAlt, 'General', 'Outline')
pushSVG('Box', Icons.Outline.Box, 'General', 'Outline')
pushSVG('Card', Icons.Outline.Card, 'General', 'Outline')
pushSVG('Shopping Cart', Icons.Outline.ShopCart, 'General', 'Outline')
pushSVG('Wallet', Icons.Outline.Wallet, 'General', 'Outline')
pushSVG('Bank', Icons.Outline.Bank, 'General', 'Outline', ['Temple'])
pushSVG('Sun', Icons.Outline.Sun, 'General', 'Outline', ['Light', 'Bright', 'Day'])
pushSVG('Moon', Icons.Outline.Moon, 'General', 'Outline', ['Dark', 'Night'])
pushSVG('Pallete', Icons.Outline.Palette, 'General', 'Outline', ['Cookie'])
pushSVG('Flask', Icons.Outline.Flask, 'General', 'Outline', ['Beaker'])
pushSVG('Flask-Alt', Icons.Outline.FlaskAlt, 'General', 'Outline')
pushSVG('Shopping Basket', Icons.Outline.ShopBasket, 'General', 'Outline')
pushSVG('Shopping Bag', Icons.Outline.ShopBag, 'General', 'Outline')
pushSVG('Pulse', Icons.Outline.Pulse, 'General', 'Outline', ['Heartbeat'])
pushSVG('Umbrella', Icons.Outline.Umbrella, 'General', 'Outline', ['Rain'])
pushSVG('Calender', Icons.Outline.Calender, 'General', 'Outline')
pushSVG('Filter', Icons.Outline.Filter, 'General', 'Outline', ['Funnel'])
pushSVG('Medikit', Icons.Outline.Medikit, 'General', 'Outline', ['First Aid'])
pushSVG('Clock', Icons.Outline.Clock, 'General', 'Outline')
pushSVG('Alarm', Icons.Outline.Alarm, 'General', 'Outline')
pushSVG('Timer', Icons.Outline.Timer, 'General', 'Outline', ['Stopwatch'])

//Status
pushSVG('Lock', Icons.Outline.Lock, 'Status', 'Outline')
pushSVG('Unlock', Icons.Outline.Unlock, 'Status', 'Outline')
pushSVG('Lock-Time', Icons.Outline.LockTime, 'Status', 'Outline')
pushSVG('Eye', Icons.Outline.Eye, 'Status', 'Outline', ['Password'])
pushSVG('Eye-Closed', Icons.Outline.EyeClosed, 'Status', 'Outline', ['Password'])
pushSVG('Key', Icons.Outline.Key, 'Status', 'Outline')
pushSVG('Pin', Icons.Outline.Pin, 'Status', 'Outline')
pushSVG('Lightening', Icons.Outline.Lightn, 'Status', 'Outline', ['Shock'])
pushSVG('Lightening-Alt', Icons.Outline.LightnAlt, 'Status', 'Outline')
pushSVG('Shield', Icons.Outline.Shield, 'Status', 'Outline')
pushSVG('Info-Rectangle', Icons.Outline.InfoRect, 'Status', 'Outline')
pushSVG('Info-Circle', Icons.Outline.InfoCic, 'Status', 'Outline')
pushSVG('Info-Triangle', Icons.Outline.InfoTri, 'Status', 'Outline', ['Warning'])
pushSVG('Checked Box', Icons.Outline.CheckedBox, 'Status', 'Outline')
pushSVG('Star', Icons.Outline.Star, 'Status', 'Outline', ['Rate'])
pushSVG('Star-Half', Icons.Outline.StarHalf, 'Status', 'Outline', ['Rate'])
pushSVG('Diamond', Icons.Outline.Diamond, 'Status', 'Outline')
pushSVG('Notification', Icons.Outline.Notif, 'Status', 'Outline', ['Bell'])
pushSVG('Notification-On', Icons.Outline.NotifOn, 'Status', 'Outline', ['Bell', 'Alarm', 'Ring'])
pushSVG('Notification-Off', Icons.Outline.NotifOff, 'Status', 'Outline', ['Bell', 'Alarm'])
pushSVG('Heart', Icons.Outline.Heart, 'Status', 'Outline', ['Love'])
pushSVG('Heart-Off', Icons.Outline.HeartOff, 'Status', 'Outline')
pushSVG('Heart-Plus', Icons.Outline.HeartPlus, 'Status', 'Outline')
pushSVG('Heartbeat', Icons.Outline.Heartbeat, 'Status', 'Outline')
pushSVG('FIre', Icons.Outline.Fire, 'Status', 'Outline', ['Flame'])
pushSVG('Power Button', Icons.Outline.PowerBtn, 'Status', 'Outline', ['Off'])
pushSVG('Lightbulb-Alt', Icons.Outline.LightAlt, 'Status', 'Outline')
pushSVG('Lightbulb', Icons.Outline.Light, 'Status', 'Outline')
pushSVG('Lightbulb-Off', Icons.Outline.LightOff, 'Status', 'Outline')
pushSVG('Award', Icons.Outline.Award, 'Status', 'Outline', ['Badge'])
pushSVG('Sand Watch', Icons.Outline.SandWatch, 'Status', 'Outline', ['Houglass'])
pushSVG('Present', Icons.Outline.Present, 'Status', 'Outline', ['Gift'])
pushSVG('Toggle-On', Icons.Outline.ToggleOn, 'Status', 'Outline', ['Switch'])
pushSVG('Toggle-Off', Icons.Outline.ToggleOff, 'Status', 'Outline', ['Switch'])
pushSVG('University', Icons.Outline.Uni, 'Status', 'Outline', ['Graduation'])
pushSVG('Bookmark', Icons.Outline.BookmarkStat, 'Status', 'Outline')
pushSVG('Book-Open', Icons.Outline.BookOpen, 'Status', 'Outline')

//Communication
pushSVG('Envelope', Icons.Outline.Envelope, 'Communication', 'Outline', ['Mail'])
pushSVG('Envelope-Open', Icons.Outline.EnvelopeOpen, 'Communication', 'Outline', ['Mail'])
pushSVG('Contacts', Icons.Outline.Contacts, 'Communication', 'Outline', ['Phone', 'Book'])
pushSVG('User', Icons.Outline.User, 'Communication', 'Outline')
pushSVG('User-Clock', Icons.Outline.UserClock, 'Communication', 'Outline')
pushSVG('User-Plus', Icons.Outline.UserPlus, 'Communication', 'Outline')
pushSVG('User-Block', Icons.Outline.UserBlock, 'Communication', 'Outline')
pushSVG('Like', Icons.Outline.Like, 'Communication', 'Outline', ['Thumbs-up'])
pushSVG('Disike', Icons.Outline.Dislike, 'Communication', 'Outline', ['Thumbs-Down'])
pushSVG('Chat', Icons.Outline.Chat, 'Communication', 'Outline', ['Comment', 'Bubble'])
pushSVG('Comment', Icons.Outline.Comment, 'Communication', 'Outline', ['Chat', 'Bubble'])
pushSVG('Comment-Plus', Icons.Outline.CommentPlus, 'Communication', 'Outline', ['Chat', 'Bubble'])
pushSVG('Comment-Minus', Icons.Outline.CommentMinus, 'Communication', 'Outline', ['Chat', 'Bubble'])
pushSVG('Comment-Block', Icons.Outline.CommentBlock, 'Communication', 'Outline', ['Chat', 'Bubble'])
pushSVG('Phone', Icons.Outline.Phone, 'Communication', 'Outline')
pushSVG('Phone-Miss', Icons.Outline.PhoneMiss, 'Communication', 'Outline', ['Missed-call'])
pushSVG('Phone-Off', Icons.Outline.PhoneOff, 'Communication', 'Outline', ['Call Blocked'])
pushSVG('Phone-In', Icons.Outline.PhoneIn, 'Communication', 'Outline', ['Call'])
pushSVG('Phone-Out', Icons.Outline.PhoneOut, 'Communication', 'Outline', ['Call'])
pushSVG('Send', Icons.Outline.Send, 'Communication', 'Outline')
pushSVG('Share', Icons.Outline.Share, 'Communication', 'Outline')
pushSVG('Forward', Icons.Outline.Forward, 'Communication', 'Outline')
pushSVG('Reply', Icons.Outline.Reply, 'Communication', 'Outline', ['Back'])
pushSVG('Bullhorn', Icons.Outline.Bullhorn, 'Communication', 'Outline', ['Loudspeaker'])
pushSVG('Share-Box', Icons.Outline.ShareBox, 'Communication', 'Outline')

//Media
pushSVG('Headset', Icons.Outline.Headset, 'Media', 'Outline')
pushSVG('Headphones', Icons.Outline.HeadPs, 'Media', 'Outline')
pushSVG('Play', Icons.Outline.Play, 'Media', 'Outline')
pushSVG('Pause', Icons.Outline.Pause, 'Media', 'Outline')
pushSVG('Fast-Forward', Icons.Outline.FastFWD, 'Media', 'Outline')
pushSVG('Fast-Rewind', Icons.Outline.FastRWD, 'Media', 'Outline')
pushSVG('Skip-Next', Icons.Outline.SkipNext, 'Media', 'Outline')
pushSVG('Skip-Previous', Icons.Outline.SkipPrev, 'Media', 'Outline')
pushSVG('Microphone', Icons.Outline.Mic, 'Media', 'Outline')
pushSVG('Microphone-Off', Icons.Outline.MicOff, 'Media', 'Outline')
pushSVG('Music', Icons.Outline.Music, 'Media', 'Outline', ['Note'])
pushSVG('Volume-Up', Icons.Outline.VolUp, 'Media', 'Outline', ['Speaker'])
pushSVG('Volume-Down', Icons.Outline.VolDown, 'Media', 'Outline', ['Speaker'])
pushSVG('Volume-Off', Icons.Outline.VolOff, 'Media', 'Outline', ['Speaker'])
pushSVG('Shuffle', Icons.Outline.Shuffle, 'Media', 'Outline')

//Files
pushSVG('File', Icons.Outline.File, 'Files', 'Outline')
pushSVG('Document', Icons.Outline.Document, 'Files', 'Outline')
pushSVG('Picture', Icons.Outline.Pic, 'Files', 'Outline')
pushSVG('File-User', Icons.Outline.FileUser, 'Files', 'Outline')
pushSVG('File-Upload', Icons.Outline.FileUL, 'Files', 'Outline')
pushSVG('File-Download', Icons.Outline.FileDL, 'Files', 'Outline')
pushSVG('Invoice', Icons.Outline.Invoice, 'Files', 'Outline')
pushSVG('Clipboard', Icons.Outline.Clip, 'Files', 'Outline')
pushSVG('Clipboard-Alt', Icons.Outline.ClipAlt, 'Files', 'Outline')
pushSVG('Image', Icons.Outline.Image, 'Files', 'Outline', ['Picture'])
pushSVG('Folder', Icons.Outline.Folder, 'Files', 'Outline')
pushSVG('Folder-Open', Icons.Outline.FolderOpen, 'Files', 'Outline')
pushSVG('Folder-Locked', Icons.Outline.FolderLock, 'Files', 'Outline')
pushSVG('Folder-Plus', Icons.Outline.FolderPlus, 'Files', 'Outline')
pushSVG('Folder-Delete', Icons.Outline.FolderDelete, 'Files', 'Outline')
pushSVG('Folder-User', Icons.Outline.FolderUser, 'Files', 'Outline')
pushSVG('Folder-Blocked', Icons.Outline.FolderBlock, 'Files', 'Outline')
pushSVG('Book', Icons.Outline.Book, 'Files', 'Outline')
pushSVG('Book-Checked', Icons.Outline.BookCheck, 'Files', 'Outline')
pushSVG('Bookmarked', Icons.Outline.Bookmark, 'Files', 'Outline')
pushSVG('Cloud', Icons.Outline.Cloud, 'Files', 'Outline')
pushSVG('Cloud-Checked', Icons.Outline.CloudCheck, 'Files', 'Outline')
pushSVG('Cloud-Upload', Icons.Outline.CloudUL, 'Files', 'Outline')
pushSVG('Cloud-Download', Icons.Outline.CloudDL, 'Files', 'Outline')
pushSVG('Cloud-Off', Icons.Outline.CloudOff, 'Files', 'Outline')
pushSVG('Copy', Icons.Outline.Copy, 'Files', 'Outline', ['Duplicate'])
pushSVG('Upload', Icons.Outline.Upload, 'Files', 'Outline')
pushSVG('Download', Icons.Outline.Download, 'Files', 'Outline')

//Interface
pushSVG('Caret-Left', Icons.Outline.CarLeft, 'Interface', 'Outline')
pushSVG('Caret-Right', Icons.Outline.CarRight, 'Interface', 'Outline')
pushSVG('Caret-Up', Icons.Outline.CarUp, 'Interface', 'Outline')
pushSVG('Caret-Down', Icons.Outline.CarDown, 'Interface', 'Outline')
pushSVG('Arrow-Left', Icons.Outline.ArrLeft, 'Interface', 'Outline')
pushSVG('Arrow-Right', Icons.Outline.ArrRight, 'Interface', 'Outline')
pushSVG('Arrow-Up', Icons.Outline.ArrUp, 'Interface', 'Outline')
pushSVG('Arrow-Down', Icons.Outline.ArrDown, 'Interface', 'Outline')
pushSVG('Check', Icons.Outline.Check, 'Interface', 'Outline', ['Correct'])
pushSVG('Refresh', Icons.Outline.Refresh, 'Interface', 'Outline')
pushSVG('Menu', Icons.Outline.Menu, 'Interface', 'Outline', ['Lines', 'Bars'])
pushSVG('Search', Icons.Outline.Search, 'Interface', 'Outline', ['Wave'])
pushSVG('Hotspot', Icons.Outline.Hotspot, 'Interface', 'Outline')
pushSVG('Attach', Icons.Outline.Attach, 'Interface', 'Outline', ['Link'])
pushSVG('Other-1', Icons.Outline.Other1, 'Interface', 'Outline', ['Menu', 'Dots'])
pushSVG('Other-2', Icons.Outline.Other2, 'Interface', 'Outline', ['Menu', 'Dots'])
pushSVG('Expand', Icons.Outline.Expand, 'Interface', 'Outline', ['Maximise'])
pushSVG('Collapse', Icons.Outline.Collapse, 'Interface', 'Outline', ['Minimise', 'Shrink'])
pushSVG('Exchange', Icons.Outline.Exchange, 'Interface', 'Outline')
pushSVG('Sort', Icons.Outline.Sort, 'Interface', 'Outline')
pushSVG('Plus', Icons.Outline.Plus, 'Interface', 'Outline', ['Add'])
pushSVG('Cross', Icons.Outline.Cross, 'Interface', 'Outline', ['X', 'Cancel'])
pushSVG('Move', Icons.Outline.Move, 'Interface', 'Outline')
pushSVG('Bluetooth', Icons.Outline.BlueTt, 'Interface', 'Outline')
pushSVG('At-Sign', Icons.Outline.AtSign, 'Interface', 'Outline', ['Mention'])
pushSVG('Login', Icons.Outline.Login, 'Interface', 'Outline', ['Signin'])
pushSVG('Logout', Icons.Outline.Logout, 'Interface', 'Outline', ['Signout'])
pushSVG('Save', Icons.Outline.Save, 'Interface', 'Outline', ['Floppy', 'Disk'])
pushSVG('Edit', Icons.Outline.Edit, 'Interface', 'Outline')
pushSVG('Edit-Alt', Icons.Outline.EditAlt, 'Interface', 'Outline', ['Pencil'])
pushSVG('Layout', Icons.Outline.Layout, 'Interface', 'Outline', ['Menu', 'Grid', 'Squares'])
pushSVG('Rows', Icons.Outline.Rows, 'Interface', 'Outline')
pushSVG('Columns', Icons.Outline.Cols, 'Interface', 'Outline', ['Bars'])
pushSVG('Apps', Icons.Outline.Apps, 'Interface', 'Outline', ['Grid', 'Menu'])
pushSVG('Settings-Alt', Icons.Outline.SettingsAlt, 'Interface', 'Outline')
pushSVG('Settings', Icons.Outline.Settings, 'Interface', 'Outline')
pushSVG('Trash', Icons.Outline.Trash, 'Interface', 'Outline', ['Bin'])
pushSVG('Trash-Alt', Icons.Outline.TrashAlt, 'Interface', 'Outline')
pushSVG('Cancel', Icons.Outline.Cancel, 'Interface', 'Outline', ['X', 'Cross'])
pushSVG('Add', Icons.Outline.Add, 'Interface', 'Outline', ['Plus'])
pushSVG('Zoom-In', Icons.Outline.ZoomIn, 'Interface', 'Outline', ['Magnify'])
pushSVG('Zoom-Out', Icons.Outline.ZoomOut, 'Interface', 'Outline', ['Magnify'])
pushSVG('Stack', Icons.Outline.Stack, 'Interface', 'Outline', ['Layers'])
pushSVG('Cursor', Icons.Outline.Cursor, 'Interface', 'Outline')
pushSVG('Backspace', Icons.Outline.Backspace, 'Interface', 'Outline')
pushSVG('Settings-Adjust', Icons.Outline.SettingAdj, 'Interface', 'Outline', ['Tools'])
pushSVG('History', Icons.Outline.History, 'Interface', 'Outline')

//Devices
pushSVG('Printer', Icons.Outline.Printer, 'Devices', 'Outline')
pushSVG('Desktop', Icons.Outline.Desktop, 'Devices', 'Outline', ['Monitor', 'iMac'])
pushSVG('Mobile Phone', Icons.Outline.MobileP, 'Devices', 'Outline', ['Android', 'iPhone'])
pushSVG('Watch', Icons.Outline.Watch, 'Devices', 'Outline')
pushSVG('Gamepad', Icons.Outline.Gamepad, 'Devices', 'Outline', ['Controller', 'Joystick'])
pushSVG('Server', Icons.Outline.Server, 'Devices', 'Outline', ['Drives'])
pushSVG('Processor', Icons.Outline.Processor, 'Devices', 'Outline', ['CPU'])
pushSVG('Mouse-Alt', Icons.Outline.MouseAlt, 'Devices', 'Outline')
pushSVG('Mouse', Icons.Outline.Mouse, 'Devices', 'Outline')
pushSVG('Binoculars', Icons.Outline.Binos, 'Devices', 'Outline')
pushSVG('Battery-Empty', Icons.Outline.BattEmpty, 'Devices', 'Outline')
pushSVG('Ballety-Low', Icons.Outline.BattLow, 'Devices', 'Outline')
pushSVG('Battery-Quater', Icons.Outline.BattQuat, 'Devices', 'Outline')
pushSVG('Battery-Half', Icons.Outline.BattHalf, 'Devices', 'Outline')
pushSVG('Battery-Most', Icons.Outline.BattMost, 'Devices', 'Outline')
pushSVG('Battery-Full', Icons.Outline.BattFull, 'Devices', 'Outline')
pushSVG('Camera', Icons.Outline.Camera, 'Devices', 'Outline')
pushSVG('Video', Icons.Outline.Video, 'Devices', 'Outline', ['Recorder'])
pushSVG('Dialpad', Icons.Outline.Dialpad, 'Devices', 'Outline')

//Location
pushSVG('Location', Icons.Outline.Location, 'Navigation', 'Outline')
pushSVG('Location-Check', Icons.Outline.LocationCheck, 'Navigation', 'Outline')
pushSVG('Location-Plus', Icons.Outline.LocationPlus, 'Navigation', 'Outline')
pushSVG('Location-Question', Icons.Outline.LocationQtn, 'Navigation', 'Outline')
pushSVG('Explore', Icons.Outline.Explore, 'Navigation', 'Outline', ['Compass'])
pushSVG('Current Location', Icons.Outline.CurrLocation, 'Navigation', 'Outline', ['Point'])
pushSVG('Navigation', Icons.Outline.Navgation, 'Navigation', 'Outline')
pushSVG('Globe', Icons.Outline.Globe, 'Navigation', 'Outline')
pushSVG('Map Location', Icons.Outline.MapLocation, 'Navigation', 'Outline')

///Brands
pushSVG('Apple', Icons.Outline.Apple, 'Brands', 'Outline')
pushSVG('Dribble', Icons.Outline.Dribble, 'Brands', 'Outline')
pushSVG('Google Drive', Icons.Outline.GoogleDrive, 'Brands', 'Outline')
pushSVG('YouTube', Icons.Outline.YT, 'Brands', 'Outline', ['Google'])
pushSVG('Skype', Icons.Outline.Skype, 'Brands', 'Outline')
pushSVG('Pinterest', Icons.Outline.Pinterest, 'Brands', 'Outline')
pushSVG('Google Chrome', Icons.Outline.Chrome, 'Brands', 'Outline')
pushSVG('Facebook', Icons.Outline.FB, 'Brands', 'Outline', ['Meta'])
pushSVG('Tumblr', Icons.Outline.Tumblr, 'Brands', 'Outline')
pushSVG('Snapchat', Icons.Outline.Snap, 'Brands', 'Outline')
pushSVG('Linkedin', Icons.Outline.Linkedin, 'Brands', 'Outline')
pushSVG('Figma', Icons.Outline.Figma, 'Brands', 'Outline')
pushSVG('Sketch', Icons.Outline.Sketch, 'Brands', 'Outline')
pushSVG('Twitter', Icons.Outline.Twitter, 'Brands', 'Outline', ['Birdapp'])
pushSVG('VK Ontakte', Icons.Outline.VK, 'Brands', 'Outline')
pushSVG('Google Play', Icons.Outline.GooglePlay, 'Brands', 'Outline')
pushSVG('App Store', Icons.Outline.AppStore, 'Brands', 'Outline', ['Store'])
pushSVG('Twitch', Icons.Outline.Twitch, 'Brands', 'Outline')
pushSVG('Google', Icons.Outline.Google, 'Brands', 'Outline')
pushSVG('Telegram', Icons.Outline.Telegram, 'Brands', 'Outline')
pushSVG('Whatsapp', Icons.Outline.Whatsapp, 'Brands', 'Outline', ['Meta'])
pushSVG('Viber', Icons.Outline.Viber, 'Brands', 'Outline')
pushSVG('Messenger', Icons.Outline.Messenger, 'Brands', 'Outline', ['Meta'])
pushSVG('Group 151', Icons.Outline.Group151, 'Brands', 'Outline')
pushSVG('Reddit', Icons.Outline.Reddit, 'Brands', 'Outline')
pushSVG('QQ', Icons.Outline.QQ, 'Brands', 'Outline')
pushSVG('Android', Icons.Outline.Android, 'Brands', 'Outline', ['Google'])
pushSVG('Dropbox', Icons.Outline.Dropbox, 'Brands', 'Outline')
pushSVG('Gmail', Icons.Outline.Gmail, 'Brands', 'Outline', ['Google'])
pushSVG('Google Alt', Icons.Outline.GoogleAlt, 'Brands', 'Outline')
pushSVG('Slack', Icons.Outline.Slack, 'Brands', 'Outline')
pushSVG('Adobe Photoshop', Icons.Outline.PS, 'Brands', 'Outline', ['PS'])
pushSVG('Adobe Illustrator', Icons.Outline.AI, 'Brands', "Outline", ["AI"])
pushSVG('Adobe Expirience Design', Icons.Outline.XD, 'Brands', "Outline", ['XD'])
pushSVG('Adobe After Effects', Icons.Outline.AE, 'Brands', "Outline", ['AE'])
pushSVG('Adobe Indesign', Icons.Outline.ID, 'Brands', "Outline", ['ID'])
pushSVG('Adobe Lightroom', Icons.Outline.LR, 'Brands', "Outline", ['LR'])
pushSVG('Adobe Premiere', Icons.Outline.PR, 'Brands', 'Outline', ['PR'])
pushSVG('Adobe Indesign-1', Icons.Outline.ID1, 'Brands', "Outline", ['ID'])
pushSVG('Behance', Icons.Outline.Behance, 'Brands', 'Outline', ['Adobe'])
pushSVG('Windows', Icons.Outline.Windows, 'Brands', 'Outline', ['Miscrosoft'])
pushSVG('Asana', Icons.Outline.Asana, 'Brands', 'Outline')
pushSVG('Trello', Icons.Outline.Trello, 'Brands', 'Outline')
pushSVG('Medium', Icons.Outline.Medium, 'Brands', 'Outline')
pushSVG('Notion', Icons.Outline.Notion, 'Brands', 'Outline')

///Solid

//General
pushSVG('Home', Icons.Solid.Home, 'General', 'Solid')
pushSVG('Bag', Icons.Solid.Bag, 'General', 'Solid', ['Suitcase'])
pushSVG('Pie Chart', Icons.Solid.ChartPie, 'General', 'Solid')
pushSVG('Pie Chart-Alt', Icons.Solid.ChartPieAlt, 'General', 'Solid')
pushSVG('Box', Icons.Solid.Box, 'General', 'Solid')
pushSVG('Card', Icons.Solid.Card, 'General', 'Solid')
pushSVG('Shopping Cart', Icons.Solid.ShopCart, 'General', 'Solid')
pushSVG('Wallet', Icons.Solid.Wallet, 'General', 'Solid')
pushSVG('Bank', Icons.Solid.Bank, 'General', 'Solid', ['Temple'])
pushSVG('Sun', Icons.Solid.Sun, 'General', 'Solid', ['Light', 'Bright', 'Day'])
pushSVG('Moon', Icons.Solid.Moon, 'General', 'Solid', ['Dark', 'Night'])
pushSVG('Pallete', Icons.Solid.Palette, 'General', 'Solid', ['Cookie'])
pushSVG('Flask', Icons.Solid.Flask, 'General', 'Solid', ['Beaker'])
pushSVG('Flask-Alt', Icons.Solid.FlaskAlt, 'General', 'Solid')
pushSVG('Shopping Basket', Icons.Solid.ShopBasket, 'General', 'Solid')
pushSVG('Shopping Bag', Icons.Solid.ShopBag, 'General', 'Solid')
pushSVG('Pulse', Icons.Solid.Pulse, 'General', 'Solid', ['Heartbeat'])
pushSVG('Umbrella', Icons.Solid.Umbrella, 'General', 'Solid', ['Rain'])
pushSVG('Calender', Icons.Solid.Calender, 'General', 'Solid')
pushSVG('Filter', Icons.Solid.Filter, 'General', 'Solid', ['Funnel'])
pushSVG('Medikit', Icons.Solid.Medikit, 'General', 'Solid', ['First Aid'])
pushSVG('Clock', Icons.Solid.Clock, 'General', 'Solid')
pushSVG('Alarm', Icons.Solid.Alarm, 'General', 'Solid')
pushSVG('Timer', Icons.Solid.Timer, 'General', 'Solid', ['Stopwatch'])

//Status
pushSVG('Lock', Icons.Solid.Lock, 'Status', 'Solid')
pushSVG('Unlock', Icons.Solid.Unlock, 'Status', 'Solid')
pushSVG('Lock-Time', Icons.Solid.LockTime, 'Status', 'Solid')
pushSVG('Eye', Icons.Solid.Eye, 'Status', 'Solid', ['Password'])
pushSVG('Eye-Closed', Icons.Solid.EyeClosed, 'Status', 'Solid', ['Password'])
pushSVG('Key', Icons.Solid.Key, 'Status', 'Solid')
pushSVG('Pin', Icons.Solid.Pin, 'Status', 'Solid')
pushSVG('Lightening', Icons.Solid.Lightn, 'Status', 'Solid', ['Shock'])
pushSVG('Lightening-Alt', Icons.Solid.LightnAlt, 'Status', 'Solid')
pushSVG('Shield', Icons.Solid.Shield, 'Status', 'Solid')
pushSVG('Info-Rectangle', Icons.Solid.InfoRect, 'Status', 'Solid')
pushSVG('Info-Circle', Icons.Solid.InfoCic, 'Status', 'Solid')
pushSVG('Info-Triangle', Icons.Solid.InfoTri, 'Status', 'Solid', ['Warning'])
pushSVG('Checked Box', Icons.Solid.CheckedBox, 'Status', 'Solid')
pushSVG('Star', Icons.Solid.Star, 'Status', 'Solid', ['Rate'])
pushSVG('Star-Half', Icons.Solid.StarHalf, 'Status', 'Solid', ['Rate'])
pushSVG('Diamond', Icons.Solid.Diamond, 'Status', 'Solid')
pushSVG('Notification', Icons.Solid.Notif, 'Status', 'Solid', ['Bell'])
pushSVG('Notification-On', Icons.Solid.NotifOn, 'Status', 'Solid', ['Bell', 'Alarm', 'Ring'])
pushSVG('Notification-Off', Icons.Solid.NotifOff, 'Status', 'Solid', ['Bell', 'Alarm'])
pushSVG('Heart', Icons.Solid.Heart, 'Status', 'Solid', ['Love'])
pushSVG('Heart-Off', Icons.Solid.HeartOff, 'Status', 'Solid')
pushSVG('Heart-Plus', Icons.Solid.Group23, 'Status', 'Solid')
pushSVG('Heartbeat', Icons.Solid.Heartbeat, 'Status', 'Solid')
pushSVG('Fire', Icons.Solid.Fire, 'Status', 'Solid', ['Flame'])
pushSVG('Power Button', Icons.Solid.PowerBtn, 'Status', 'Solid', ['Off'])
pushSVG('Lightbulb-Alt', Icons.Solid.LightAlt, 'Status', 'Solid')
pushSVG('Lightbulb', Icons.Solid.Light, 'Status', 'Solid')
pushSVG('Lightbulb-Off', Icons.Solid.LightOff, 'Status', 'Solid')
pushSVG('Award', Icons.Solid.Award, 'Status', 'Solid', ['Badge'])
pushSVG('Sand Watch', Icons.Solid.SandWatch, 'Status', 'Solid', ['Houglass'])
pushSVG('Present', Icons.Solid.Present, 'Status', 'Solid', ['Gift'])
pushSVG('Toggle-On', Icons.Solid.ToggleOn, 'Status', 'Solid', ['Switch'])
pushSVG('Toggle-Off', Icons.Solid.ToggleOff, 'Status', 'Solid', ['Switch'])
pushSVG('University', Icons.Solid.Uni, 'Status', 'Solid', ['Graduation'])
pushSVG('Bookmark', Icons.Solid.BookmarkStat, 'Status', 'Solid')
pushSVG('Book-Open', Icons.Solid.BookOpen, 'Status', 'Solid')

//Communication
pushSVG('Envelope', Icons.Solid.Envelope, 'Communication', 'Solid', ['Mail'])
pushSVG('Envelope-Open', Icons.Solid.EnvelopeOpen, 'Communication', 'Solid', ['Mail'])
pushSVG('Contacts', Icons.Solid.Contacts, 'Communication', 'Solid', ['Phone', 'Book'])
pushSVG('User', Icons.Solid.User, 'Communication', 'Solid')
pushSVG('User-Clock', Icons.Solid.UserClock, 'Communication', 'Solid')
pushSVG('User-Plus', Icons.Solid.UserPlus, 'Communication', 'Solid')
pushSVG('User-Block', Icons.Solid.UserBlock, 'Communication', 'Solid')
pushSVG('Like', Icons.Solid.Like, 'Communication', 'Solid', ['Thumbs-up'])
pushSVG('Disike', Icons.Solid.Dislike, 'Communication', 'Solid', ['Thumbs-Down'])
pushSVG('Chat', Icons.Solid.Chat, 'Communication', 'Solid', ['Comment', 'Bubble'])
pushSVG('Comment', Icons.Solid.Comment, 'Communication', 'Solid', ['Chat', 'Bubble'])
pushSVG('Comment-Plus', Icons.Solid.CommentPlus, 'Communication', 'Solid', ['Chat', 'Bubble'])
pushSVG('Comment-Minus', Icons.Solid.CommentMinus, 'Communication', 'Solid', ['Chat', 'Bubble'])
pushSVG('Comment-Block', Icons.Solid.CommentBlock, 'Communication', 'Solid', ['Chat', 'Bubble'])
pushSVG('Phone', Icons.Solid.Phone, 'Communication', 'Solid')
pushSVG('Phone-Miss', Icons.Solid.PhoneMiss, 'Communication', 'Solid', ['Missed-call'])
pushSVG('Phone-Off', Icons.Solid.PhoneOff, 'Communication', 'Solid', ['Call Blocked'])
pushSVG('Phone-In', Icons.Solid.PhoneIn, 'Communication', 'Solid', ['Call'])
pushSVG('Phone-Out', Icons.Solid.PhoneOut, 'Communication', 'Solid', ['Call'])
pushSVG('Send', Icons.Solid.Send, 'Communication', 'Solid')
pushSVG('Share', Icons.Solid.Share, 'Communication', 'Solid')
pushSVG('Forward', Icons.Solid.Forward, 'Communication', 'Solid')
pushSVG('Reply', Icons.Solid.Reply, 'Communication', 'Solid', ['Back'])
pushSVG('Bullhorn', Icons.Solid.Bullhorn, 'Communication', 'Solid', ['Loudspeaker'])
pushSVG('Share-Box', Icons.Solid.ShareBox, 'Communication', 'Solid')

//Media
pushSVG('Headset', Icons.Solid.Headset, 'Media', 'Solid')
pushSVG('Headphones', Icons.Solid.HeadPs, 'Media', 'Solid')
pushSVG('Play', Icons.Solid.Play, 'Media', 'Solid')
pushSVG('Pause', Icons.Solid.Pause, 'Media', 'Solid')
pushSVG('Fast-Forward', Icons.Solid.FastFWD, 'Media', 'Solid')
pushSVG('Fast-Rewind', Icons.Solid.FastRWD, 'Media', 'Solid')
pushSVG('Skip-Next', Icons.Solid.SkipNext, 'Media', 'Solid')
pushSVG('Skip-Previous', Icons.Solid.SkipPrev, 'Media', 'Solid')
pushSVG('Microphone', Icons.Solid.Mic, 'Media', 'Solid')
pushSVG('Microphone-Off', Icons.Solid.MicOff, 'Media', 'Solid')
pushSVG('Music', Icons.Solid.Music, 'Media', 'Solid', ['Note'])
pushSVG('Volume-Up', Icons.Solid.VolUp, 'Media', 'Solid', ['Speaker'])
pushSVG('Volume-Down', Icons.Solid.VolDown, 'Media', 'Solid', ['Speaker'])
pushSVG('Volume-Off', Icons.Solid.VolOff, 'Media', 'Solid', ['Speaker'])
pushSVG('Shuffle', Icons.Solid.Shuffle, 'Media', 'Solid')

//Files
pushSVG('File', Icons.Solid.File, 'Files', 'Solid')
pushSVG('Document', Icons.Solid.Document, 'Files', 'Solid')
pushSVG('Picture', Icons.Solid.Pic, 'Files', 'Solid')
pushSVG('File-User', Icons.Solid.FileUser, 'Files', 'Solid')
pushSVG('File-Upload', Icons.Solid.FileUL, 'Files', 'Solid')
pushSVG('File-Download', Icons.Solid.FileDL, 'Files', 'Solid')
pushSVG('Invoice', Icons.Solid.Invoice, 'Files', 'Solid')
pushSVG('Clipboard', Icons.Solid.Clip, 'Files', 'Solid')
pushSVG('Clipboard-Alt', Icons.Solid.ClipAlt, 'Files', 'Solid')
pushSVG('Image', Icons.Solid.Image, 'Files', 'Solid', ['Picture'])
pushSVG('Folder', Icons.Solid.Folder, 'Files', 'Solid')
pushSVG('Folder-Open', Icons.Solid.FolderOpen, 'Files', 'Solid')
pushSVG('Folder-Locked', Icons.Solid.FolderLock, 'Files', 'Solid')
pushSVG('Folder-Plus', Icons.Solid.FolderPlus, 'Files', 'Solid')
pushSVG('Folder-Delete', Icons.Solid.FolderDelete, 'Files', 'Solid')
pushSVG('Folder-User', Icons.Solid.FolderUser, 'Files', 'Solid')
pushSVG('Folder-Blocked', Icons.Solid.FolderBlock, 'Files', 'Solid')
pushSVG('Book', Icons.Solid.Book, 'Files', 'Solid')
pushSVG('Book-Checked', Icons.Solid.BookCheck, 'Files', 'Solid')
pushSVG('Bookmarked', Icons.Solid.Bookmark, 'Files', 'Solid')
pushSVG('Cloud', Icons.Solid.Cloud, 'Files', 'Solid')
pushSVG('Cloud-Checked', Icons.Solid.CloudCheck, 'Files', 'Solid')
pushSVG('Cloud-Upload', Icons.Solid.CloudUL, 'Files', 'Solid')
pushSVG('Cloud-Download', Icons.Solid.CloudDL, 'Files', 'Solid')
pushSVG('Cloud-Off', Icons.Solid.CloudOff, 'Files', 'Solid')
pushSVG('Copy', Icons.Solid.Copy, 'Files', 'Solid', ['Duplicate'])
pushSVG('Upload', Icons.Solid.Upload, 'Files', 'Solid')
pushSVG('Download', Icons.Solid.Download, 'Files', 'Solid')

//Interface
pushSVG('Caret-Left', Icons.Solid.CarLeft, 'Interface', 'Solid')
pushSVG('Caret-Right', Icons.Solid.CarRight, 'Interface', 'Solid')
pushSVG('Caret-Up', Icons.Solid.CarUp, 'Interface', 'Solid')
pushSVG('Caret-Down', Icons.Solid.CarDown, 'Interface', 'Solid')
pushSVG('Arrow-Left', Icons.Solid.ArrLeft, 'Interface', 'Solid')
pushSVG('Arrow-Right', Icons.Solid.ArrRight, 'Interface', 'Solid')
pushSVG('Arrow-Up', Icons.Solid.ArrUp, 'Interface', 'Solid')
pushSVG('Arrow-Down', Icons.Solid.ArrDown, 'Interface', 'Solid')
pushSVG('Check', Icons.Solid.Check, 'Interface', 'Solid', ['Correct'])
pushSVG('Refresh', Icons.Solid.Refresh, 'Interface', 'Solid')
pushSVG('Menu', Icons.Solid.Menu, 'Interface', 'Solid', ['Lines', 'Bars'])
pushSVG('Search', Icons.Solid.Search, 'Interface', 'Solid', ['Magnify'])
pushSVG('Hotspot', Icons.Solid.Hotspot, 'Interface', 'Solid', ['Waves'])
pushSVG('Attach', Icons.Solid.Attach, 'Interface', 'Solid', ['Link'])
pushSVG('Other-1', Icons.Solid.Other1, 'Interface', 'Solid', ['Menu', 'Dots'])
pushSVG('Other-2', Icons.Solid.Other2, 'Interface', 'Solid', ['Menu', 'Dots'])
pushSVG('Expand', Icons.Solid.Expand, 'Interface', 'Solid', ['Maximise'])
pushSVG('Collapse', Icons.Solid.Collapse, 'Interface', 'Solid', ['Minimise', 'Shrink'])
pushSVG('Exchange', Icons.Solid.Exchange, 'Interface', 'Solid')
pushSVG('Sort', Icons.Solid.Sort, 'Interface', 'Solid')
pushSVG('Plus', Icons.Solid.Plus, 'Interface', 'Solid', ['Add'])
pushSVG('Cross', Icons.Solid.Cross, 'Interface', 'Solid', ['X', 'Cancel'])
pushSVG('Move', Icons.Solid.Move, 'Interface', 'Solid')
pushSVG('Bluetooth', Icons.Solid.BlueTt, 'Interface', 'Solid')
pushSVG('At-Sign', Icons.Solid.AtSign, 'Interface', 'Solid', ['Mention'])
pushSVG('Login', Icons.Solid.Login, 'Interface', 'Solid', ['Signin'])
pushSVG('Logout', Icons.Solid.Logout, 'Interface', 'Solid', ['Signout'])
pushSVG('Save', Icons.Solid.Save, 'Interface', 'Solid', ['Floppy', 'Diskette'])
pushSVG('Edit', Icons.Solid.Edit, 'Interface', 'Solid')
pushSVG('Edit-Alt', Icons.Solid.EditAlt, 'Interface', 'Solid', ['Pencil'])
pushSVG('Layout', Icons.Solid.Layout, 'Interface', 'Solid', ['Menu', 'Grid', 'Squares'])
pushSVG('Rows', Icons.Solid.Rows, 'Interface', 'Solid')
pushSVG('Columns', Icons.Solid.Cols, 'Interface', 'Solid', ['Bars'])
pushSVG('Apps', Icons.Solid.Apps, 'Interface', 'Solid', ['Grid', 'Menu'])
pushSVG('Settings-Alt', Icons.Solid.SettingsAlt, 'Interface', 'Solid')
pushSVG('Settings', Icons.Solid.Settings, 'Interface', 'Solid')
pushSVG('Trash', Icons.Solid.Trash, 'Interface', 'Solid', ['Bin'])
pushSVG('Trash-Alt', Icons.Solid.TrashAlt, 'Interface', 'Solid')
pushSVG('Cancel', Icons.Solid.Cancel, 'Interface', 'Solid', ['X', 'Cross'])
pushSVG('Add', Icons.Solid.Add, 'Interface', 'Solid', ['Plus'])
pushSVG('Zoom-In', Icons.Solid.ZoomIn, 'Interface', 'Solid', ['Magnify'])
pushSVG('Zoom-Out', Icons.Solid.ZoomOut, 'Interface', 'Solid', ['Magnify'])
pushSVG('Stack', Icons.Solid.Stack, 'Interface', 'Solid', ['Layers'])
pushSVG('Cursor', Icons.Solid.Cursor, 'Interface', 'Solid')
pushSVG('Backspace', Icons.Solid.Backspace, 'Interface', 'Solid')
pushSVG('Settings-Adjust', Icons.Solid.SettingAdj, 'Interface', 'Solid', ['Tools'])
pushSVG('History', Icons.Solid.History, 'Interface', 'Solid')

//Devices
pushSVG('Printer', Icons.Solid.Printer, 'Devices', 'Solid')
pushSVG('Desktop', Icons.Solid.Desktop, 'Devices', 'Solid', ['Monitor', 'iMac'])
pushSVG('Mobile Phone', Icons.Solid.MobileP, 'Devices', 'Solid', ['Android', 'iPhone'])
pushSVG('Watch', Icons.Solid.Watch, 'Devices', 'Solid')
pushSVG('Gamepad', Icons.Solid.Gamepad, 'Devices', 'Solid', ['Controller', 'Joystick'])
pushSVG('Server', Icons.Solid.Server, 'Devices', 'Solid', ['Drives'])
pushSVG('Processor', Icons.Solid.Processor, 'Devices', 'Solid', ['CPU'])
pushSVG('Mouse-Alt', Icons.Solid.MouseAlt, 'Devices', 'Solid')
pushSVG('Mouse', Icons.Solid.Mouse, 'Devices', 'Solid')
pushSVG('Binoculars', Icons.Solid.Binos, 'Devices', 'Solid')
pushSVG('Battery-Empty', Icons.Solid.BattFull1, 'Devices', 'Solid')
pushSVG('Ballety-Low', Icons.Solid.BattLow, 'Devices', 'Solid')
pushSVG('Battery-Quater', Icons.Solid.BattQuat, 'Devices', 'Solid')
pushSVG('Battery-Half', Icons.Solid.BattHalf, 'Devices', 'Solid')
pushSVG('Battery-Most', Icons.Solid.BattMost, 'Devices', 'Solid')
pushSVG('Battery-Full', Icons.Solid.BattFull, 'Devices', 'Solid')
pushSVG('Camera', Icons.Solid.Camera, 'Devices', 'Solid')
pushSVG('Video', Icons.Solid.Video, 'Devices', 'Solid', ['Recorder'])
pushSVG('Dialpad', Icons.Solid.Dialpad, 'Devices', 'Solid')

//Location
pushSVG('Location', Icons.Solid.Location, 'Navigation', 'Solid')
pushSVG('Location-Check', Icons.Solid.LocationCheck, 'Navigation', 'Solid')
pushSVG('Location-Plus', Icons.Solid.LocationPlus, 'Navigation', 'Solid')
pushSVG('Location-Question', Icons.Solid.LocationQtn, 'Navigation', 'Solid')
pushSVG('Explore', Icons.Solid.Explore, 'Navigation', 'Solid', ['Compass'])
pushSVG('Current Location', Icons.Solid.CurrLocation, 'Navigation', 'Solid', ['Point'])
pushSVG('Navigation', Icons.Solid.Navgation, 'Navigation', 'Solid')
pushSVG('Globe', Icons.Solid.Globe, 'Navigation', 'Solid')
pushSVG('Map Location', Icons.Solid.MapLocation, 'Navigation', 'Solid')

///Brands
pushSVG('Apple', Icons.Solid.Apple, 'Brands', 'Solid')
pushSVG('Dribble', Icons.Solid.Dribble, 'Brands', 'Solid')
pushSVG('Google Drive', Icons.Solid.GoogleDrive, 'Brands', 'Solid')
pushSVG('YouTube', Icons.Solid.YT, 'Brands', 'Solid', ['Google'])
pushSVG('Skype', Icons.Solid.Skype, 'Brands', 'Solid')
pushSVG('Pinterest', Icons.Solid.Pinterest, 'Brands', 'Solid')
pushSVG('Google Chrome', Icons.Solid.Chrome, 'Brands', 'Solid')
pushSVG('Facebook', Icons.Solid.FB, 'Brands', 'Solid', ['Meta'])
pushSVG('Tumblr', Icons.Solid.Tumblr, 'Brands', 'Solid')
pushSVG('Snapchat', Icons.Solid.Snap, 'Brands', 'Solid')
pushSVG('Linkedin', Icons.Solid.Linkedin, 'Brands', 'Solid')
pushSVG('Figma', Icons.Solid.Figma, 'Brands', 'Solid')
pushSVG('Sketch', Icons.Solid.Sketch, 'Brands', 'Solid')
pushSVG('Twitter', Icons.Solid.Twitter, 'Brands', 'Solid', ['Birdapp'])
pushSVG('VK Ontakte', Icons.Solid.VK, 'Brands', 'Solid')
pushSVG('Google Play', Icons.Solid.GooglePlay, 'Brands', 'Solid')
pushSVG('App Store', Icons.Solid.AppStore, 'Brands', 'Solid', ['Store'])
pushSVG('Twitch', Icons.Solid.Twitch, 'Brands', 'Solid')
pushSVG('Google', Icons.Solid.Google, 'Brands', 'Solid')
pushSVG('Telegram', Icons.Solid.Telegram, 'Brands', 'Solid')
pushSVG('Whatsapp', Icons.Solid.Whatsapp, 'Brands', 'Solid', ['Meta'])
pushSVG('Viber', Icons.Solid.Viber, 'Brands', 'Solid')
pushSVG('Messenger', Icons.Solid.Messenger, 'Brands', 'Solid', ['Meta'])
pushSVG('Group 151', Icons.Solid.Wechat, 'Brands', 'Solid')
pushSVG('Reddit', Icons.Solid.Reddit, 'Brands', 'Solid')
pushSVG('QQ', Icons.Solid.QQ, 'Brands', 'Solid')
pushSVG('Android', Icons.Solid.Android, 'Brands', 'Solid', ['Google'])
pushSVG('Dropbox', Icons.Solid.Dropbox, 'Brands', 'Solid')
pushSVG('Gmail', Icons.Solid.Gmail, 'Brands', 'Solid', ['Google'])
pushSVG('Google Alt', Icons.Solid.GoogleAlt, 'Brands', 'Solid')
pushSVG('Slack', Icons.Solid.Slack, 'Brands', 'Solid')
pushSVG('Adobe Photoshop', Icons.Solid.PS, 'Brands', 'Solid', ['PS'])
pushSVG('Adobe Illustrator', Icons.Solid.AI, 'Brands', "Solid", ["AI"])
pushSVG('Adobe Expirience Design', Icons.Solid.XD, 'Brands', "Solid", ['XD'])
pushSVG('Adobe After Effects', Icons.Solid.AE, 'Brands', "Solid", ['AE'])
pushSVG('Adobe Indesign', Icons.Solid.ID, 'Brands', "Solid", ['ID'])
pushSVG('Adobe Lightroom', Icons.Solid.LR, 'Brands', "Solid", ['LR'])
pushSVG('Adobe Premiere', Icons.Solid.PR, 'Brands', 'Solid', ['PR'])
pushSVG('Adobe Indesign-1', Icons.Solid.ID1, 'Brands', "Solid", ['ID'])
pushSVG('Behance', Icons.Solid.Behance, 'Brands', 'Solid', ['Adobe'])
pushSVG('Windows', Icons.Solid.Windows, 'Brands', 'Solid', ['Miscrosoft'])
pushSVG('Asana', Icons.Solid.Asana, 'Brands', 'Solid')
pushSVG('Trello', Icons.Solid.Trello, 'Brands', 'Solid')
pushSVG('Medium', Icons.Solid.Medium, 'Brands', 'Solid')
pushSVG('Notion', Icons.Solid.Notion, 'Brands', 'Solid')
pushSVG('Craftwork', Icons.Solid.Craftwork, 'Brands', 'Solid')


//Feather Icons
pushSVG('Airplay', Icons.Feather.Airplay, 'Feather Icons', 'Outline')
pushSVG('Alert-Octagon', Icons.Feather.AlertOct, 'Feather Icons', 'Outline')
pushSVG('Align-Centre', Icons.Feather.AlignC, 'Feather Icons', 'Outline')
pushSVG('Align-Justify', Icons.Feather.AlignJ, 'Feather Icons', 'Outline')
pushSVG('Align-Left', Icons.Feather.AlignL, 'Feather Icons', 'Outline')
pushSVG('Align-Right', Icons.Feather.AlignR, 'Feather Icons', 'Outline')
pushSVG('Anchor', Icons.Feather.Anchor, 'Feather Icons', 'Outline')
pushSVG('Archive', Icons.Feather.Archive, 'Feather Icons', 'Outline', ['Box'])
pushSVG('Arrow-Left-Circle', Icons.Feather.ArrLC, 'Feather Icons', 'Outline')
pushSVG('Arrow-Right-Circle', Icons.Feather.ArrRC, 'Feather Icons', 'Outline')
pushSVG('Arrow-Down-Circle', Icons.Feather.ArrDC, 'Feather Icons', 'Outline')
pushSVG('Arrow-Up-Circle', Icons.Feather.ArrUC, 'Feather Icons', 'Outline')
pushSVG('Arrow-Up-Left', Icons.Feather.ArrUL, 'Feather Icons', 'Outline')
pushSVG('Arrow-Up-Right', Icons.Feather.ArrUR, 'Feather Icons', 'Outline')
pushSVG('Arrow-Down-Left', Icons.Feather.ArrDL, 'Feather Icons', 'Outline')
pushSVG('Arrow-Down-Right', Icons.Feather.ArrDR, 'Feather Icons', 'Outline')
pushSVG('Aperture', Icons.Feather.Aperture, 'Feather Icons', 'Outline', ['Camera'])
pushSVG('Award-2', Icons.Feather.AwardF, 'Feather Icons', 'Outline')
pushSVG('Barchart', Icons.Feather.Barchart, 'Feather Icons', 'Outline')
pushSVG('Barchart-2', Icons.Feather.Barchart2, 'Feather Icons', 'Outline')
pushSVG('Battery-Charging', Icons.Feather.BatCharge, 'Feather Icons', 'Outline')
pushSVG('Bold', Icons.Feather.Bold, 'Feather Icons', 'Outline')
pushSVG('Book', Icons.Feather.BookF, 'Feather Icons', 'Outline')
pushSVG('Chevron-Left', Icons.Feather.ChevL, 'Feather Icons', 'Outline')
pushSVG('Chevron-Right', Icons.Feather.ChevR, 'Feather Icons', 'Outline')
pushSVG('Chevron-Up', Icons.Feather.ChevUp, 'Feather Icons', 'Outline')
pushSVG('Chevron-Down', Icons.Feather.ChevDown, 'Feather Icons', 'Outline')
pushSVG('Circle', Icons.Feather.Circle, 'Feather Icons', 'Outline')
pushSVG('Cloud-Drizzle', Icons.Feather.CloudDrizzle, 'Feather Icons', 'Outline')
pushSVG('Cloud-Snow', Icons.Feather.CloudSnow, 'Feather Icons', 'Outline')
pushSVG('Cloud-Rain', Icons.Feather.CloudRain, 'Feather Icons', 'Outline')
pushSVG('Cloud-Lightining', Icons.Feather.CloudLight, 'Feather Icons', 'Outline')
pushSVG('Code', Icons.Feather.Code, 'Feather Icons', 'Outline')
pushSVG('Codepen', Icons.Feather.Codepen, 'Feather Icons', 'Outline')
pushSVG('Codesandbox', Icons.Feather.Codesandbox, 'Feather Icons', 'Outline')
pushSVG('Coffee', Icons.Feather.Coffee, 'Feather Icons', 'Outline', ['Cup'])
pushSVG('Corner-Left-Down', Icons.Feather.CornerLD, 'Feather Icons', 'Outline')
pushSVG('Corner-Right-Down', Icons.Feather.CornerRD, 'Feather Icons', 'Outline')
pushSVG('Corner-Left-Up', Icons.Feather.CornerLU, 'Feather Icons', 'Outline')
pushSVG('Corner-Right-Up', Icons.Feather.CornerRU, 'Feather Icons', 'Outline')
pushSVG('Corner-Down-Left', Icons.Feather.CornerDL, 'Feather Icons', 'Outline')
pushSVG('Corner-Down-Right', Icons.Feather.CornerDR, 'Feather Icons', 'Outline')
pushSVG('Corner-Up-Left', Icons.Feather.CornerUL, 'Feather Icons', 'Outline')
pushSVG('Corner-Up-Right', Icons.Feather.CornerUR, 'Feather Icons', 'Outline')
pushSVG('Command', Icons.Feather.Command, 'Feather Icons', 'Outline')
pushSVG('Crop', Icons.Feather.Crop, 'Feather Icons', 'Outline')
pushSVG('Crosshair', Icons.Feather.Crosshair, 'Feather Icons', 'Outline')
pushSVG('Database', Icons.Feather.DB, 'Feather Icons', 'Outline', ['DB'])
pushSVG('Disc', Icons.Feather.Disc, 'Feather Icons', 'Outline')
pushSVG('Dollar Sign', Icons.Feather.DollarS, 'Feather Icons', 'Outline', ['Money', 'Currency'])
pushSVG('Droplet', Icons.Feather.Droplet, 'Feather Icons', 'Outline', ['Rain'])
pushSVG('Edit-2', Icons.Feather.Edit2, 'Feather Icons', 'Outline')
pushSVG('External Link', Icons.Feather.ExtLink, 'Feather Icons', 'Outline')
pushSVG('Feather', Icons.Feather.Feather, 'Feather Icons', 'Outline')
pushSVG('File-Plus', Icons.Feather.FilePlus, 'Feather Icons', 'Outline')
pushSVG('File-Minus', Icons.Feather.FileMinus, 'Feather Icons', 'Outline')
pushSVG('Film', Icons.Feather.Film, 'Feather Icons', 'Outline')
pushSVG('Flag', Icons.Feather.Flag, 'Feather Icons', 'Outline')
pushSVG('Framer', Icons.Feather.Framer, 'Feather Icons', 'Outline')
pushSVG('Frown', Icons.Feather.Frown, 'Feather Icons', 'Outline', ['Simely', 'Face', 'Reaction'])
pushSVG('Meh', Icons.Feather.Meh, 'Feather Icons', 'Outline', ['Simely', 'Face', 'Reaction'])
pushSVG('Smile', Icons.Feather.Smile, 'Feather Icons', 'Outline', ['Face', 'Reaction'])
pushSVG('Git Branch', Icons.Feather.GitBranch, 'Feather Icons', 'Outline', ['Github'])
pushSVG('Git Commit', Icons.Feather.GitCommit, 'Feather Icons', 'Outline', ['Github'])
pushSVG('Git Merge', Icons.Feather.GitMerge, 'Feather Icons', 'Outline', ['Github'])
pushSVG('Git Pull', Icons.Feather.GitPull, 'Feather Icons', 'Outline', ['Github'])
pushSVG('Gitlab', Icons.Feather.Gitlab, 'Feather Icons', 'Outline', ['Github'])
pushSVG('Github', Icons.Feather.Github, 'Feather Icons', 'Outline')
pushSVG('Globe', Icons.Feather.Globe, 'Feather Icons', 'Outline')
pushSVG('Hard Drive', Icons.Feather.HardDrive, 'Feather Icons', 'Outline')
pushSVG('Hash', Icons.Feather.Hash, 'Feather Icons', 'Outline')
pushSVG('Help-Circle', Icons.Feather.HelpCirc, 'Feather Icons', 'Outline')
pushSVG('Octagon', Icons.Feather.Hex, 'Feather Icons', 'Outline')
pushSVG('Triangle', Icons.Feather.Triangle, 'Feather Icons', 'Outline')
pushSVG('Inbox', Icons.Feather.Inbox, 'Feather Icons', 'Outline')
pushSVG('Italic', Icons.Feather.Italic, 'Feather Icons', 'Outline')
pushSVG('LayoutAlt', Icons.Feather.Layout, 'Feather Icons', 'Outline')
pushSVG('Lifebuoy', Icons.Feather.LifeBouy, 'Feather Icons', 'Outline')
pushSVG('Link', Icons.Feather.Link, 'Feather Icons', 'Outline')
pushSVG('Link-2', Icons.Feather.Link2, 'Feather Icons', 'Outline')
pushSVG('Loader', Icons.Feather.Loader, 'Feather Icons', 'Outline')
pushSVG('Map', Icons.Feather.Map, 'Feather Icons', 'Outline')
pushSVG('List', Icons.Feather.List, 'Feather Icons', 'Outline')
pushSVG('Maximise-2', Icons.Feather.Maximise2, 'Feather Icons', 'Outline')
pushSVG('Minimise2-', Icons.Feather.Minimise2, 'Feather Icons', 'Outline')
pushSVG('Minus', Icons.Feather.Minus, 'Feather Icons', 'Outline')
pushSVG('Minus-Circle', Icons.Feather.MinusCirc, 'Feather Icons', 'Outline')
pushSVG('Plus-Circle', Icons.Feather.PlusCirc, 'Feather Icons', 'Outline')
pushSVG('Minus-Square', Icons.Feather.MinusSquare, 'Feather Icons', 'Outline')
pushSVG('X-Circle', Icons.Feather.XCirc, 'Feather Icons', 'Outline')
pushSVG('X-Octagon', Icons.Feather.XOct, 'Feather Icons', 'Outline')
pushSVG('Pause-Circle', Icons.Feather.PauseCirc, 'Feather Icons', 'Outline')
pushSVG('Play-Circle', Icons.Feather.PlayCirc, 'Feather Icons', 'Outline')
pushSVG('Mouse Pointer', Icons.Feather.MousePtr, 'Feather Icons', 'Outline')
pushSVG('Stop-Circle', Icons.Feather.StopCirc, 'Feather Icons', 'Outline')
pushSVG('Package', Icons.Feather.Package, 'Feather Icons', 'Outline')
pushSVG('Percentage', Icons.Feather.Percent, 'Feather Icons', 'Outline')
pushSVG('Pen Tool', Icons.Feather.PenTool, 'Feather Icons', 'Outline')
pushSVG('Phone Call', Icons.Feather.PhoneCall, 'Feather Icons', 'Outline')
pushSVG('Pocket', Icons.Feather.Pocket, 'Feather Icons', 'Outline')
pushSVG('Radio', Icons.Feather.Radio, 'Feather Icons', 'Outline', ['Waves'])
pushSVG('Refresh-Counter-Clockwise', Icons.Feather.RefreshCCW, 'Feather Icons', 'Outline')
pushSVG('Refresh-Clockwise', Icons.Feather.RefreshCW, 'Feather Icons', 'Outline')
pushSVG('Rotate-Clockwise', Icons.Feather.RotateCW, 'Feather Icons', 'Outline')
pushSVG('Repeat', Icons.Feather.Repeat, 'Feather Icons', 'Outline')
pushSVG('RSS', Icons.Feather.RSS, 'Feather Icons', 'Outline')
pushSVG('Sciccors', Icons.Feather.Sciccors, 'Feather Icons', 'Outline')
pushSVG('Sheild-Off', Icons.Feather.ShieldOff, 'Feather Icons', 'Outline')
pushSVG('Sliders', Icons.Feather.Sliders, 'Feather Icons', 'Outline')
pushSVG('Sidebar', Icons.Feather.Sidebar, 'Feather Icons', 'Outline')
pushSVG('Speaker', Icons.Feather.Speaker, 'Feather Icons', 'Outline')
pushSVG('Square', Icons.Feather.Square, 'Feather Icons', 'Outline')
pushSVG('Sunrise', Icons.Feather.Sunrise, 'Feather Icons', 'Outline')
pushSVG('Sunset', Icons.Feather.Sunset, 'Feather Icons', 'Outline')
pushSVG('Tablet', Icons.Feather.Tablet, 'Feather Icons', 'Outline')
pushSVG('TV', Icons.Feather.TV, 'Feather Icons', 'Outline')
pushSVG('Tag', Icons.Feather.Tag, 'Feather Icons', 'Outline')
pushSVG('Terminal', Icons.Feather.Terminal, 'Feather Icons', 'Outline')
pushSVG('Themometer', Icons.Feather.Thermometer, 'Feather Icons', 'Outline')
pushSVG('Target', Icons.Feather.Target, 'Feather Icons', 'Outline')
pushSVG('Tool', Icons.Feather.Tool, 'Feather Icons', 'Outline')
pushSVG('Trending-Up', Icons.Feather.TrendUp, 'Feather Icons', 'Outline')
pushSVG('Trending-Down', Icons.Feather.TrendDW, 'Feather Icons', 'Outline')
pushSVG('Truck', Icons.Feather.Truck, 'Feather Icons', 'Outline', ['Vehicle'])
pushSVG('Type', Icons.Feather.Type, 'Feather Icons', 'Outline', ['I'])
pushSVG('Underline', Icons.Feather.Underline, 'Feather Icons', 'Outline')
pushSVG('Users', Icons.Feather.Users, 'Feather Icons', 'Outline')
pushSVG('User-Check', Icons.Feather.UserCheck, 'Feather Icons', 'Outline')
pushSVG('User-Minus', Icons.Feather.UserMinus, 'Feather Icons', 'Outline')
pushSVG('User-X', Icons.Feather.UserX, 'Feather Icons', 'Outline')
pushSVG('Video-Off', Icons.Feather.VideoOff, 'Feather Icons', 'Outline')
pushSVG('Voicemail', Icons.Feather.Voicemail, 'Feather Icons', 'Outline')
pushSVG('Volume', Icons.Feather.Volume, 'Feather Icons', 'Outline')
pushSVG('Wifi', Icons.Feather.Wifi, 'Feather Icons', 'Outline')
pushSVG('Wifi-Off', Icons.Feather.WifiOff, 'Feather Icons', 'Outline')
pushSVG('Zapp-Off', Icons.Feather.ZapOff, 'Feather Icons', 'Outline', ['Lightining'])

//Edge
pushSVG('Battery Charging', Icons.Edge.BattCharge, 'Edge Icons', 'Outline')
pushSVG('CalenderAlt', Icons.Edge.Calender, 'Edge Icons', 'Outline', ['Agenda'])
pushSVG('Calender-Check', Icons.Edge.CalenderCHK, 'Edge Icons', 'Outline')
pushSVG('Cash', Icons.Edge.Cash, 'Edge Icons', 'Outline', ['Money', 'Currency'])
pushSVG('Euro', Icons.Edge.Euro, 'Edge Icons', 'Outline', ['Money', 'Currency'])
pushSVG('Pound', Icons.Edge.Pound, 'Edge Icons', 'Outline', ['Money', 'Currency'])
pushSVG('Ruble', Icons.Edge.Ruble, 'Edge Icons', 'Outline', ['Money', 'Currency'])
pushSVG('Yen', Icons.Edge.Yen, 'Edge Icons', 'Outline', ['Money', 'Currency'])
pushSVG('Coins', Icons.Edge.Coins, 'Edge Icons', 'Outline', ['Money', 'Currency'])
pushSVG('Chart-Histogram', Icons.Edge.ChartHis, 'Edge Icons', 'Outline')
pushSVG('Chart-Line', Icons.Edge.ChartLine, 'Edge Icons', 'Outline')
pushSVG('Presentation', Icons.Edge.Presentation, 'Edge Icons', 'Outline')
pushSVG('Sitemap', Icons.Edge.Sitemap, 'Edge Icons', 'Outline')
pushSVG('Comment-r', Icons.Edge.CommentR, 'Edge Icons', 'Outline', ['Chat'])
pushSVG('Comments', Icons.Edge.Comments, 'Edge Icons', 'Outline', ['Chat'])
pushSVG('Cup', Icons.Edge.Cup, 'Edge Icons', 'Outline')
pushSVG('Dashboard', Icons.Edge.Dash, 'Edge Icons', 'Outline')
pushSVG('Flag-Alt', Icons.Edge.FlagAlt, 'Edge Icons', 'Outline')
pushSVG('Folder-Check', Icons.Edge.FolderCheck, 'Edge Icons', 'Outline')
pushSVG('Gear', Icons.Edge.Gear, 'Edge Icons', 'Outline')
pushSVG('Link-r', Icons.Edge.Linkr, 'Edge Icons', 'Outline')
pushSVG('No Entry', Icons.Edge.NoEntry, 'Edge Icons', 'Outline', ['Cone'])
pushSVG('Plane', Icons.Edge.Plane, 'Edge Icons', 'Outline')
pushSVG('Rocket', Icons.Edge.Rocket, 'Edge Icons', 'Outline')
pushSVG('Phone-r', Icons.Edge.Phoner, 'Edge Icons', 'Outline')
pushSVG('Question-Circle', Icons.Edge.QtnCirc, 'Edge Icons', 'Outline')
pushSVG('Shield-Check', Icons.Edge.SheildChk, 'Edge Icons', 'Outline')

//Extract Categories from Icons
export const categories = [...new Set(icons.map((icon) => icon.category))];

export default icons